/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiensIndexRouteImport } from './routes/biens.index'
import { Route as BiensIdRouteImport } from './routes/biens.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensIndexRoute = BiensIndexRouteImport.update({
  id: '/biens/',
  path: '/biens/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensIdRoute = BiensIdRouteImport.update({
  id: '/biens/$id',
  path: '/biens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/biens/$id': typeof BiensIdRoute
  '/biens/': typeof BiensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/biens/$id': typeof BiensIdRoute
  '/biens': typeof BiensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/biens/$id': typeof BiensIdRoute
  '/biens/': typeof BiensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/login'
    | '/services'
    | '/biens/$id'
    | '/biens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/login'
    | '/services'
    | '/biens/$id'
    | '/biens'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/login'
    | '/services'
    | '/biens/$id'
    | '/biens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  BiensIdRoute: typeof BiensIdRoute
  BiensIndexRoute: typeof BiensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/': {
      id: '/biens/'
      path: '/biens'
      fullPath: '/biens/'
      preLoaderRoute: typeof BiensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/$id': {
      id: '/biens/$id'
      path: '/biens/$id'
      fullPath: '/biens/$id'
      preLoaderRoute: typeof BiensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  BiensIdRoute: BiensIdRoute,
  BiensIndexRoute: BiensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
