/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiensIndexRouteImport } from './routes/biens.index'
import { Route as BiensIdRouteImport } from './routes/biens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensIndexRoute = BiensIndexRouteImport.update({
  id: '/biens/',
  path: '/biens/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensIdRoute = BiensIdRouteImport.update({
  id: '/biens/$id',
  path: '/biens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biens/$id': typeof BiensIdRoute
  '/biens/': typeof BiensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biens/$id': typeof BiensIdRoute
  '/biens': typeof BiensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biens/$id': typeof BiensIdRoute
  '/biens/': typeof BiensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biens/$id' | '/biens/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biens/$id' | '/biens'
  id: '__root__' | '/' | '/biens/$id' | '/biens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiensIdRoute: typeof BiensIdRoute
  BiensIndexRoute: typeof BiensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/': {
      id: '/biens/'
      path: '/biens'
      fullPath: '/biens/'
      preLoaderRoute: typeof BiensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/$id': {
      id: '/biens/$id'
      path: '/biens/$id'
      fullPath: '/biens/$id'
      preLoaderRoute: typeof BiensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiensIdRoute: BiensIdRoute,
  BiensIndexRoute: BiensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
